first profile layout done
webanwendung-on18/effective-octo-waffle pull request #20
Opened 2020-01-29 15:09 UTC by NataschaForster

#Issue
#5 

#Description
Das erste Layout der Profil-Seite ist fertig

#Additional information
* Rezept-Karten müssen noch hinzugefügt werden
* Sammlungen müssen noch zum Component gemacht werden
* Navbar und Footer werden hinzugefügt, sobald fertig

2020-01-29 17:11 UTC, eisenils approved these changes
LGTM 👍

2020-01-29 17:23 UTC, felixkeller98 commented on src/components/CollectionPreview.js
> +          <a
Den <a>-Tag müsste man noch durch ein <Link />-Component ausstasuschen :)

2020-01-29 17:25 UTC, 1-Felix requested changes
Die `<a>`-Tags noch durch die <Link />austauschen pls :)

2020-01-29 17:25 UTC, felixkeller98 commented on src/components/CollectionPreview.js
> +          <a href="#!" className="black-text d-flex justify-content-end">
Hier auch

2020-01-29 17:25 UTC, felixkeller98 commented on src/components/RecipePreview.js
> +                    href="#!"
Hier auch

2020-02-02 09:40 UTC, 1-Felix approved these changes
Sieht gut aus! 😃

Wir müssen nur daran denken das Profil noch nur noch auf die `profile/{userId}`-Url umziehen, damit man dann auch andere Profile besuchen kann. 
Dafür könnte man eigtl. auch eine Issue machen :)

Von mir aus kann man das hier aber schon mal mergen 👍

2020-02-02 10:57 UTC, merged