[WIP] Feature/recipe
webanwendung-on18/effective-octo-waffle pull request #35
Opened 2020-02-02 18:34 UTC by felixkeller98

# Description
Hier ist schon mal die Recipe-Komponente an die Datenbank angebunden.

2020-02-03 16:42 UTC, felixkeller98 commented
Ich würde das hier schon mal merge, damit die Grundlogik für die Recipe-Seite schon mal auf dem `develop` ist. 
Also pls approven wenn's okay ist 😃

2020-02-04 08:52 UTC, eisenils requested changes
See comments 👓

2020-02-04 08:52 UTC, eisenils commented on src/components/Recipe.js
> +      description
Never used -> wird auskommentiert

2020-02-04 08:52 UTC, eisenils commented on src/components/Recipe.js
> +      this.setState({ laoding: true });
laoding? Ich glaube eher `loading` 😉

2020-02-04 09:00 UTC, merged