Implement recipe details
webanwendung-on18/effective-octo-waffle pull request #44
Opened 2020-02-06 08:52 UTC by eisenils

Die Rezept-Detailseite ist für das erste fertig. Bitte mal drüber schauen und approven. Merci ✔️

2020-02-06 10:17 UTC, NataschaForster approved these changes

2020-02-06 18:10 UTC, 1-Felix requested changes
Sieht gut aus, I like it! :)

2020-02-06 18:10 UTC, felixkeller98 commented on src/components/Recipe.js
> +                    <div class="polaroid">
bitte noch in `className` ändern

2020-02-07 08:33 UTC, eisenils commented on src/components/Recipe.js
> +                    <div class="polaroid">
gefixed 👍

2020-02-07 08:33 UTC, merged