Feature/servings
webanwendung-on18/effective-octo-waffle pull request #73
Opened 2020-02-21 12:58 UTC by NataschaForster

* Description

Added scalable servings functionality on recipe view.

2020-02-21 17:27 UTC, 1-Felix requested changes
Ich bin bisschen verwirrt. Sieht so aus als wäre dieser Branch auf basis einer alten Version von `feature/profilesettings` erstellt wurden?
Nicht das wir deine schönen Änderungen auf dem Profil, mit diesem Merge wieder überschreiben :o

(Ich schau mal wie man das am besten lösen könnte)

2020-02-21 18:56 UTC, 1-Felix approved these changes
So ich glaub' dieses Branch-Problemchen ist jetzt gelöst.

Hab nur noch eine überflüssige Variable im State gefunden. c:

2020-02-21 18:56 UTC, felixkeller98 commented on src/components/Recipe.js
> +      currentIngredient: "",
```suggestion
```

2020-02-22 09:40 UTC, eisenils approved these changes

2020-02-25 16:07 UTC, merged