Feature/feed Styling
webanwendung-on18/effective-octo-waffle pull request #76
Opened 2020-02-22 11:49 UTC by OleMantei

# Description
- überarbeitet Aussehen Filter
- überarbeitet Aussehen Rezepte

2020-02-22 11:54 UTC, OleMantei commented
![Bildschirmfoto 2020-02-22 um 12 53 52](https://user-images.githubusercontent.com/48588093/75091875-6f4a6280-5572-11ea-8002-eab27e958549.png)
![Bildschirmfoto 2020-02-22 um 12 53 41](https://user-images.githubusercontent.com/48588093/75091878-707b8f80-5572-11ea-8359-178160c07767.png)

2020-02-22 11:58 UTC, OleMantei commented
![Bildschirmfoto 2020-02-22 um 12 58 06](https://user-images.githubusercontent.com/48588093/75091932-ff88a780-5572-11ea-84bf-6d5c71ca5438.png)
![Bildschirmfoto 2020-02-22 um 12 57 57](https://user-images.githubusercontent.com/48588093/75091934-01eb0180-5573-11ea-9120-482ce8ba40dc.png)

2020-02-24 14:42 UTC, eisenils requested changes
Die suggestions würde ich gerne nochmal mit allen besprechen. Sind nur Kleinigkeiten. Der Rest ist echt klasse 👍

2020-02-24 14:42 UTC, eisenils commented on src/components/RefinementList.js
> +                    color="secondary"
Ich weiß nicht, ob ich das mag 🤷🏼‍♂️
Vielleicht doch lieber `primary`?
```suggestion
                    color="primary"
```

2020-02-24 14:42 UTC, eisenils commented on src/sass/layout/_Feed.scss
> +  border-radius: 0px 30px 30px 0px;
Wir haben eigentlich alles eckig gestaltet. Das fällt etwas aus dem Rahmen
```suggestion
```

2020-02-24 17:11 UTC, OleMantei commented
> Die suggestions würde ich gerne nochmal mit allen besprechen. Sind nur Kleinigkeiten. Der Rest ist echt klasse 👍

Danke für dein Feedback :) Ja machen wir.

2020-02-27 09:32 UTC, 1-Felix approved these changes
Nice 👍

2020-02-27 09:33 UTC, merged